name: Organize files

on:
  workflow_run:
    workflows: ["Auto Update"]
    types:
      - completed
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'DreamGallery/Campus-adv-ass'
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Move files
      run: |
        python scripts/move.py

    - name: Commit changes
      id: asset-auto-commit-action
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Organize files"